pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIAL_ID = 'mlops-jenkins-dockerhub-token'
        DOCKERHUB_REGISTRY = 'https://registry.hub.docker.com'
        DOCKERHUB_REPOSITORY = 'dariusztrawicki/mlops-proj-01'
        GITHUB_CREDENTIAL_ID = 'mlops-github-token'
        GITHUB_REPO_URL = 'https://github.com/dariusz-trawicki/mlops-jenkins-tf.git'
        GITHUB_BRANCH = '*/main'
    }
    stages {
        stage('Clone Repository') {
            steps {
                script {
                    echo 'Cloning GitHub Repository...'
                    checkout scmGit(
                        branches: [[name: "${GITHUB_BRANCH}"]],
                        extensions: [],
                        userRemoteConfigs: [[
                            credentialsId: "${GITHUB_CREDENTIAL_ID}",
                            url: "${GITHUB_REPO_URL}"
                        ]]
                    )
                }
            }
        }
        stage('Lint Code') {
            steps {
                // Lint code
                script {
                    echo 'Linting Python Code...'
                    sh "python -m pip install --break-system-packages -r requirements.txt"
                    sh "python -m pylint app.py train.py --output=pylint-report.txt --exit-zero"
                    sh "python -m flake8 app.py train.py --ignore=E501,E302 --output-file=flake8-report.txt"
                    sh "python -m black app.py train.py"
                }
            }
        }
        stage('Test Code') {
            steps {
                // Pytest code
                script {
                    echo 'Testing Python Code...'
                    sh "python -m pytest tests/"
                }
            }
        }
        stage('Trivy FS Scan') {
            steps {
                script {
                    echo 'Scannning Filesystem with Trivy...'
                    sh "trivy fs --format table --output trivy-fs-report.html ./"
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    echo 'Building Docker Image...'
                    sh """
                        docker buildx create --use --name multiplatform --driver docker-container || true
                        docker buildx build \
                        --platform linux/amd64 \
                        -t ${DOCKERHUB_REPOSITORY}:latest \
                        --load \
                        .
                    """
                }
            }
        }
        stage('Trivy Docker Image Scan') {
            steps {
                // Trivy Docker Image Scan
                script {
                    echo 'Scanning Docker Image with Trivy...'
                    sh "trivy image --format table --output trivy-image-report.html ${DOCKERHUB_REPOSITORY}:latest"
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    echo 'Pushing Docker Image to DockerHub...'
                    withCredentials([usernamePassword(
                        credentialsId: "${DOCKERHUB_CREDENTIAL_ID}",
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )]) {
                        sh """
                            echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin
                            docker push ${DOCKERHUB_REPOSITORY}:latest
                        """
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    echo 'Deploying to production...'
                    withCredentials([[
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'mlops-awscred',
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        sh """
                            AWS_PAGER='' aws ecs update-service \
                                --cluster mlops-flask-prod-cluster \
                                --service mlops-flask-prod-service \
                                --force-new-deployment \
                                --region eu-central-1
                        """
                    }
                }
            }
        }
    }
}
