apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iris-api-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:dariusz-trawicki/iris-mlops-config.git
    targetRevision: main
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: iris-prod
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers: [/spec/replicas]
