apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iris-dev

resources:
- namespace.yaml
- ../../base/iris-api

images:
- digest: sha256:e98dd6db5e55900c89d18486656564d6d344f88a9fd7b0e8062c6b1f9235fe7d
  name: iris-api-placeholder
  newName: europe-central2-docker.pkg.dev/PROJECT_ID/iris/api

configMapGenerator:
- behavior: merge
  literals:
  - MODEL_URI=gs://PROJECT_ID-models/1788787675/
  - LOG_LEVEL=INFO
  - PROMETHEUS_DISABLE_CREATED_SERIES=true
  name: iris-api-config

patches:
- path: patch-serviceaccount.yaml
- path: patch-resources.yaml
