apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: iris-api
spec:
  selector:
    matchLabels:
      app: iris-api
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
